Implement lmgtfy Command
NullDev/CSC-Bot pull request #102
Opened 2021-10-01 14:15 UTC by Insax

Either Searches the quoted entry or applied search string

2021-10-01 14:18 UTC, JanMer97 commented on src/commands/lmgtfy.js
> +exports.run = async(client, message, args, callback) => {
Doku is missing

2021-10-01 16:48 UTC, tobi6112 commented
Das was @JanMer97 sagt. Wenn schon JSDoc / TypeScript gemischt, dann sollten wir immerhin darin konsistent bleiben. Dann können wir mergen

2021-10-02 09:11 UTC, Insax commented on src/commands/lmgtfy.js
> +exports.run = async(client, message, args, callback) => {
fixed

2021-10-02 10:13 UTC, tobi6112 requested changes

2021-10-02 10:13 UTC, tobi6112 commented on src/commands/lmgtfy.js
> +    message.channel.send(reply).then(() => message.delete());
Der Part ist in meinen Augen zu verschachtelt. Ich würde sowas in die Richtung vorschlagen:

```suggestion
    if (messageRef) {
        const quotedMessage = await message.channel.messages.fetch(messageRef);
        if (!!quotedMessage.content) {
            const searchQuery = text ? buildSearchQuery(text) : buildSearchQuery(quotedMessage.content);
            reply = `Hey, ${quotedMessage.author}, du hättest auch googeln können: ${searchQuery}, danke dir ${message.author}`;
        }
        else if (!text) {
            message.channel.send("Bruder da ist nichts wonach ich suchen kann").then(() => message.delete());
            return callback;
        }
    }
    else if (text) {
        reply = `${message.author} hat es geschafft zu googeln! ${buildSearchQuery(text)}`;
    }
    
    message.channel.send(reply).then(() => message.delete());
    return callback;
```

2021-12-14 22:36 UTC, closed without merging