Refactor command loading to happen at startup
NullDev/CSC-Bot pull request #40
Opened 2021-06-17 20:37 UTC by holzmaster

Ungetestet

2021-06-18 07:04 UTC, tobi6112 requested changes

2021-06-18 07:04 UTC, tobi6112 commented on src/handler/commands.js
> +        res.set(commandFile.toLowerCase(), require(fullCommandFile));
Siehe oben. Oder hier halt 
```suggestion
        res.set(commandFile.toLowerCase().replace(/\.js$/, ""), require(fullCommandFile));
```
oder
```suggestion
        res.set(path.parse(commandFile).name, require(fullCommandFile));
```

2021-06-18 07:04 UTC, tobi6112 commented on src/handler/commands.js
> +    for(const commandFile of fs.readdirSync(commandRoot)) {
Kein fancy dancy functional loop? Das wird Shamlo aber stören...

2021-06-18 16:24 UTC, holzmaster commented on src/handler/commands.js
> +    for(const commandFile of fs.readdirSync(commandRoot)) {
Würde viel komplizierter aussehen, niemand verstehen und mindestens genauso lang sein

2021-06-18 16:24 UTC, holzmaster commented on src/handler/cmdHandler.js
> +    let cmdHandle = commandTable.get(command);
Wird auch in der Hilfe benutzt, Endung sollte nicht drin sein.

2021-06-18 16:29 UTC, tobi6112 commented on src/handler/cmdHandler.js
> +    let cmdHandle = commandTable.get(command);
In Hilfe wird die Endung ersetzt

2021-06-18 16:29 UTC, holzmaster commented on src/handler/commands.js
> +        res.set(commandFile.toLowerCase(), require(fullCommandFile));
1 nicer fund

2021-06-18 16:44 UTC, tobi6112 approved these changes
Sieht gut aus

2021-06-19 01:17 UTC, holzmaster commented
Hast du die Änderungsvorschläge eigentlich irgendwie speziell gemacht? Konnte einfach auf einen KNopf drücken und die direkt committen. War ziemlich cremig.

2021-06-19 05:48 UTC, tobi6112 commented
> Hast du die Änderungsvorschläge eigentlich irgendwie speziell gemacht? Konnte einfach auf einen KNopf drücken und die direkt committen. War ziemlich cremig.

Suggestions kannst du direkt übernehmen. Dafür einfach:

~~~

```suggestion
int x = 100;
```
~~~

2021-06-20 19:16 UTC, tobi6112 commented
Wird im Zuge der SlashCommands (#35) umgesetzt. Danke holzi!

2021-06-20 19:16 UTC, closed without merging